### ISSUE TITLE
生成静态库编译报错

### ISSUE THREAD

**Issue by lzh545** [zlgopen/awtk-widget-table-view-mvvm#1]
awtk（5月17号）+最新mvvm+指定jerryscript+最新table-view
1、直接scons编译正常
2、加上SHARED=FALSE，生成静态库编译报错，好像是jerryscript版本问题？

awtk版本：036bbd2d81e52a5f50741a9b0f7994665d9a3cfe
mvvm版本：36f65236981844c0e643fb5866e399b496b6e8be
jerryscript版本：3737a28eafd580a2bee2794e4f5edd0c0471a0c6
table-view版本：920c80a9e6bd4488ac6909f0f95a2d1f63aebeba

**Comment by xianjimli** [comment]
就编译共享库吧。

**Comment by lzh545** [comment]
> 就编译共享库吧。

李工你好，请问这个问题我直接更新或者回退jerryscript能解决么？我这边都用的静态库加载
