### ISSUE TITLE
大量打印警告`(0:0): get_var code=9 not found var`的问题还没有修复，已经提了1年了

### ISSUE THREAD

**Issue by ufbycd** [zlgopen/awtk-widget-table-view-mvvm#2]
当满足以下两种情况时就会大量打印如题警告：

1. 表格里的行数较少，填不满一屏时；
2. 拖动到表格的结尾时

记得我去年在哪里就提过这个问题。

**Comment by RainMic1019** [comment]
这是由于 table_view 控件的特性导致的，table_view 控件初始化时会提前创建好缓冲区和可视区的 item 控件，拖动滚动条时在回调函数中更新数据，在 awtk-mvvm 中， item 控件创建时就解析并保存了数据绑定规则，当滚动条拖到底后，会去获取可视区下方缓冲区控件的数据，但此时 Model 层的数组已经显示完毕，并没有这么多数据，所以就打印上述警告了。

该问题是设计上的问题，仅打印警告，不影响使用，我们需要先确认方案，暂时没那么快修复。

你如果不想看到这些警告，可以将log等级调高，或者屏蔽掉 awtk 中对应的打印代码（搜索 not found var 就可以找到）。

**Comment by ufbycd** [comment]
好吧，我先屏蔽警告。我之前还以为是ViewMode里的`size`属性设置不正确导致的小问题。
